image: erlang:19.3

before_script:
  - apt-get update -y
  - apt-get -y install g++-4.9
  - export CXX=g++-4.9

variables:
  ERL_AFLAGS: "-smp enable"

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs

  script:
    - make test

pages:
    stage: deploy
    script:
      - make test cover
      - mv _build/test/cover/ public/
    artifacts:
      paths:
        - public
      expire_in: 30 days
    only:
      - master
